const STORE_CATEGORY = {
  SUSHI: 'SUSHI',
  UNAGI: 'UNAGI',
  TEMPURA: 'TEMPURA',
  TONKATSU: 'TONKATSU',
  YAKITORI: 'YAKITORI',
  SUKIYAKI: 'SUKIYAKI',
  SOBA: 'SOBA',
  RAMEN: 'RAMEN',
  YAKISOBA: 'YAKISOBA',
  OKONOMIYAKI: 'OKONOMIYAKI',
  DONBURI: 'DONBURI',
  ODEN: 'ODEN',
  KAISEKI: 'KAISEKI',
  HAMBAGU: 'HAMBAGU',
  TEPPANYAKI: 'TEPPANYAKI',
  CURRY: 'CURRY',
  YAKINIKU: 'YAKINIKU',
  NABE: 'NABE',
  CAFE: 'CAFE',
  IZAKAYA: 'IZAKAYA',
  OTHER: 'OTHER',
};

const textByStoreCategory = {
  SUSHI: 'Sushi & Seafood',
  UNAGI: 'Eel',
  TEMPURA: 'Tempura',
  TONKATSU: 'Tonkatsu & Kushikatsu',
  YAKITORI: 'Yakitori & Skewers',
  SUKIYAKI: 'Sukiyaki & Shabu-shabu',
  SOBA: 'Soba & Udon',
  RAMEN: 'Ramen & Tsukemen',
  YAKISOBA: 'Yakisoba',
  OKONOMIYAKI: 'Okonomiyaki & Takoyaki',
  DONBURI: 'Rice Bowls',
  ODEN: 'Oden',
  KAISEKI: 'Kaiseki & Traditional Japanese Cuisine',
  HAMBAGU: 'Hamburg Steak & Omurice',
  TEPPANYAKI: 'Steak & Teppanyaki',
  CURRY: 'Curry',
  YAKINIKU: 'Yakiniku & Horumon',
  NABE: 'Hot Pot',
  CAFE: 'Cafe & Desserts',
  IZAKAYA: 'Izakaya & Bars',
  OTHER: 'Other Japanese Foods',
};

module.exports = {
  STORE_CATEGORY,
  textByStoreCategory,
};
